-- ============================================================
-- D&D CHARACTER MANAGER
-- 003 - 5etools content model
--
-- Purpose:
--   Extend the existing catalogue so it can safely import structured
--   5e.tools data without replacing the current character system.
--
-- Important:
--   This migration is additive. It does not delete or recreate the
--   existing catalogue or character data.
-- ============================================================

-- ------------------------------------------------------------
-- 0. Make the existing item value/weight fields compatible with
-- 5e.tools text values (for example `3 lb`, `15 gp`, `Priceless`).
-- This is safe on the current database where these columns have
-- already been changed to text.
-- ------------------------------------------------------------

alter table public.items
  alter column weight type text using weight::text,
  alter column value type text using value::text;


-- ------------------------------------------------------------
-- 1. Shared content-source catalogue
-- ------------------------------------------------------------

create table if not exists public.content_sources (
  id uuid primary key default gen_random_uuid(),
  code text not null,
  name text,
  edition text not null default '2014',
  source_type text not null default 'book',
  is_official boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint content_sources_edition_check
    check (edition in ('2014', '2024', 'custom')),

  unique (code, edition)
);

create index if not exists content_sources_edition_idx
  on public.content_sources (edition);


-- ------------------------------------------------------------
-- 2. Add stable 5e.tools identity + raw source data
--
-- content_key is generated by the importer and is deliberately
-- separate from the UUID primary key. This prevents name-based
-- collisions when the same named spell/item/etc. exists in more
-- than one source or ruleset.
-- ------------------------------------------------------------

alter table public.races
  add column if not exists edition text not null default '2014',
  add column if not exists content_key text,
  add column if not exists source_code text,
  add column if not exists page integer,
  add column if not exists raw_data jsonb not null default '{}'::jsonb;

alter table public.classes
  add column if not exists edition text not null default '2014',
  add column if not exists content_key text,
  add column if not exists source_code text,
  add column if not exists page integer,
  add column if not exists raw_data jsonb not null default '{}'::jsonb;

alter table public.subclasses
  add column if not exists edition text not null default '2014',
  add column if not exists content_key text,
  add column if not exists source_code text,
  add column if not exists page integer,
  add column if not exists raw_data jsonb not null default '{}'::jsonb;

alter table public.backgrounds
  add column if not exists edition text not null default '2014',
  add column if not exists content_key text,
  add column if not exists source_code text,
  add column if not exists page integer,
  add column if not exists raw_data jsonb not null default '{}'::jsonb;

alter table public.spells
  add column if not exists edition text not null default '2014',
  add column if not exists content_key text,
  add column if not exists source_code text,
  add column if not exists page integer,
  add column if not exists material_component text,
  add column if not exists raw_data jsonb not null default '{}'::jsonb;

alter table public.features
  add column if not exists edition text not null default '2014',
  add column if not exists content_key text,
  add column if not exists source_code text,
  add column if not exists page integer,
  add column if not exists raw_data jsonb not null default '{}'::jsonb;

alter table public.items
  add column if not exists edition text not null default '2014',
  add column if not exists content_key text,
  add column if not exists source_code text,
  add column if not exists page integer,
  add column if not exists raw_data jsonb not null default '{}'::jsonb;


-- ------------------------------------------------------------
-- 3. Normalise source naming
--
-- Existing rows use "source". Keep that column for backwards
-- compatibility with the current application, while the importer
-- uses source_code for the canonical 5e.tools source identifier.
-- ------------------------------------------------------------

update public.races
set source_code = source
where source_code is null and source is not null;

update public.classes
set source_code = source
where source_code is null and source is not null;

update public.subclasses
set source_code = source
where source_code is null and source is not null;

update public.backgrounds
set source_code = source
where source_code is null and source is not null;

update public.spells
set source_code = source
where source_code is null and source is not null;

update public.features
set source_code = source
where source_code is null and source is not null;

update public.items
set source_code = source
where source_code is null and source is not null;


-- ------------------------------------------------------------
-- 4. Edition checks
-- ------------------------------------------------------------

alter table public.races
  drop constraint if exists races_edition_check;

alter table public.races
  add constraint races_edition_check
  check (edition in ('2014', '2024', 'custom'));

alter table public.classes
  drop constraint if exists classes_edition_check;

alter table public.classes
  add constraint classes_edition_check
  check (edition in ('2014', '2024', 'custom'));

alter table public.subclasses
  drop constraint if exists subclasses_edition_check;

alter table public.subclasses
  add constraint subclasses_edition_check
  check (edition in ('2014', '2024', 'custom'));

alter table public.backgrounds
  drop constraint if exists backgrounds_edition_check;

alter table public.backgrounds
  add constraint backgrounds_edition_check
  check (edition in ('2014', '2024', 'custom'));

alter table public.spells
  drop constraint if exists spells_edition_check;

alter table public.spells
  add constraint spells_edition_check
  check (edition in ('2014', '2024', 'custom'));

alter table public.features
  drop constraint if exists features_edition_check;

alter table public.features
  add constraint features_edition_check
  check (edition in ('2014', '2024', 'custom'));

alter table public.items
  drop constraint if exists items_edition_check;

alter table public.items
  add constraint items_edition_check
  check (edition in ('2014', '2024', 'custom'));


-- ------------------------------------------------------------
-- 5. Stable catalogue indexes
--
-- A normal unique index is used rather than a partial unique index so
-- PostgREST can infer `on_conflict=content_key` for importer upserts.
-- PostgreSQL still allows multiple NULL values in a unique index, so
-- existing rows without a content_key remain valid.
-- ------------------------------------------------------------

drop index if exists races_content_key_uidx;
create unique index races_content_key_uidx
  on public.races (content_key);

drop index if exists classes_content_key_uidx;
create unique index classes_content_key_uidx
  on public.classes (content_key);

drop index if exists subclasses_content_key_uidx;
create unique index subclasses_content_key_uidx
  on public.subclasses (content_key);

drop index if exists backgrounds_content_key_uidx;
create unique index backgrounds_content_key_uidx
  on public.backgrounds (content_key);

drop index if exists spells_content_key_uidx;
create unique index spells_content_key_uidx
  on public.spells (content_key);

drop index if exists features_content_key_uidx;
create unique index features_content_key_uidx
  on public.features (content_key);

drop index if exists items_content_key_uidx;
create unique index items_content_key_uidx
  on public.items (content_key);


create index if not exists races_edition_source_idx
  on public.races (edition, source_code);

create index if not exists classes_edition_source_idx
  on public.classes (edition, source_code);

create index if not exists subclasses_edition_source_idx
  on public.subclasses (edition, source_code);

create index if not exists backgrounds_edition_source_idx
  on public.backgrounds (edition, source_code);

create index if not exists spells_edition_source_idx
  on public.spells (edition, source_code);

create index if not exists spells_edition_level_idx
  on public.spells (edition, level);

create index if not exists features_edition_source_idx
  on public.features (edition, source_code);

create index if not exists items_edition_source_idx
  on public.items (edition, source_code);

create unique index if not exists spell_classes_spell_class_uidx
  on public.spell_classes (spell_id, class_id);


-- ------------------------------------------------------------
-- 6. Flexible JSON search indexes
--
-- The raw_data column preserves the original 5e.tools structure.
-- This is important because 5e.tools contains nested structures
-- that should not be flattened prematurely.
-- ------------------------------------------------------------

create index if not exists spells_raw_data_gin_idx
  on public.spells using gin (raw_data);

create index if not exists features_raw_data_gin_idx
  on public.features using gin (raw_data);

create index if not exists items_raw_data_gin_idx
  on public.items using gin (raw_data);

create index if not exists classes_raw_data_gin_idx
  on public.classes using gin (raw_data);

create index if not exists races_raw_data_gin_idx
  on public.races using gin (raw_data);


-- ------------------------------------------------------------
-- 7. Import bookkeeping
--
-- One row per imported source file. This lets us re-run imports
-- safely and see exactly which 5e.tools files are installed.
-- ------------------------------------------------------------

create table if not exists public.content_imports (
  id uuid primary key default gen_random_uuid(),
  source_code text not null,
  edition text not null,
  entity_type text not null,
  source_file text not null,
  source_revision text,
  imported_at timestamptz not null default now(),
  record_count integer not null default 0,
  status text not null default 'success',
  error_message text,
  metadata jsonb not null default '{}'::jsonb,

  constraint content_imports_edition_check
    check (edition in ('2014', '2024', 'custom')),

  constraint content_imports_status_check
    check (status in ('success', 'partial', 'failed'))
);

create index if not exists content_imports_lookup_idx
  on public.content_imports (edition, entity_type, source_code);


-- ------------------------------------------------------------
-- 8. Keep updated_at working on the new tables
-- ------------------------------------------------------------

drop trigger if exists set_content_sources_updated_at
  on public.content_sources;

create trigger set_content_sources_updated_at
before update on public.content_sources
for each row
execute function public.set_updated_at();


-- ------------------------------------------------------------
-- 9. RLS for source/import metadata
--
-- Source catalogue is readable by authenticated users.
-- Import bookkeeping is readable by authenticated users but is
-- not writable from the browser. The importer will use the
-- service-side import process later.
-- ------------------------------------------------------------

alter table public.content_sources enable row level security;
alter table public.content_imports enable row level security;

drop policy if exists "Authenticated users can read content sources"
  on public.content_sources;

create policy "Authenticated users can read content sources"
on public.content_sources
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read content imports"
  on public.content_imports;

create policy "Authenticated users can read content imports"
on public.content_imports
for select
to authenticated
using (true);


-- ============================================================
-- END 003
-- ============================================================
