"use client";

import { useState } from "react";
import { Badge, PageHeader, SectionCard } from "../../components/AppShell";
import { useCharacters } from "../../context/CharacterContext";
import { items } from "../../lib/data";
import { getItemRestrictionReason, hasOverride, isItemNormallyAvailable } from "../../lib/rules";

export default function InventoryLibraryPage() {
  const { characters, accessMode, addInventoryItem } = useCharacters();
  const [characterId, setCharacterId] = useState(characters[0]?.id ?? "");
  const [search, setSearch] = useState("");
  const [showRestricted, setShowRestricted] = useState(false);
  const character = characters.find((entry) => entry.id === characterId);
  const filtered = items.filter((item) => `${item.name} ${item.category} ${item.rarity} ${item.description}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><PageHeader eyebrow="Content Library" title="Equipment Library" description="Rarity and campaign restrictions are metadata. Player Mode blocks items marked as DM-granted, while DM Mode can override them." /><SectionCard title="Filter access"><div className="flex flex-col gap-3 md:flex-row"><select value={characterId} onChange={(e) => setCharacterId(e.target.value)} className="flex-1 rounded-xl border border-stone-800 bg-stone-950 px-4 py-3 text-sm"><option value="">No character selected</option>{characters.map((c) => <option key={c.id} value={c.id}>{c.name} • Level {c.level}</option>)}</select><label className="flex items-center gap-2 px-2 text-sm text-stone-400"><input type="checkbox" checked={showRestricted} onChange={(e) => setShowRestricted(e.target.checked)} /> Show restricted</label></div><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search equipment..." className="mt-3 w-full rounded-xl border border-stone-800 bg-stone-950 px-4 py-3 text-sm outline-none focus:border-amber-400" /></SectionCard><div className="mt-6 grid gap-3 md:grid-cols-2">{filtered.map((item) => { const allowed = character ? isItemNormallyAvailable(character, item) || hasOverride(character, "item", item.id) : true; if (character && !showRestricted && !allowed) return null; const owned = character?.inventory.find((entry) => entry.itemId === item.id); return <article key={item.id} className="rounded-2xl border border-stone-800 bg-stone-900/70 p-5"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2"><h2 className="font-semibold">{item.name}</h2><Badge>{item.rarity}</Badge>{item.requiresAttunement && <Badge>Attunement</Badge>}</div><p className="mt-1 text-xs uppercase tracking-wider text-stone-600">{item.category}</p></div><Badge tone={allowed ? "good" : "warn"}>{allowed ? "Available" : "Restricted"}</Badge></div><p className="mt-3 text-sm leading-6 text-stone-400">{item.description}</p><div className="mt-2 text-xs text-stone-600">{item.weight || "No weight"} • {item.value || "No value"}</div><div className="mt-4 flex items-center justify-between gap-3">{owned ? <Badge tone="good">Owned ×{owned.quantity}</Badge> : <span />}{character ? allowed ? <button onClick={() => addInventoryItem(character.id, item.id)} className="rounded-xl bg-stone-100 px-3 py-2 text-sm font-semibold text-stone-950">+ Add</button> : accessMode === "dm" ? <button onClick={() => addInventoryItem(character.id, item.id, 1, true)} className="rounded-xl border border-amber-700 px-3 py-2 text-sm text-amber-300">DM Grant</button> : <span className="max-w-xs text-right text-xs text-stone-600">{getItemRestrictionReason(character, item)}</span> : <span className="text-xs text-stone-600">Select a character to add</span>}</div></article>; })}</div></div>;
}
